# Generated by Django 5.1.2 on 2024-10-24 10:39

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
